### ISSUE TITLE
Error Scaling Dynos

### ISSUE THREAD

**Issue by giovanibrmiguel** [dhyegocalota/visa-appointment-tracker#10]
Hi, @dhyegocalota.

I've been receiving an error message when deploying the app for the first time in Heroku:

_"Error scaling dynos: Cannot use the following dyno types in the same app: Free and Hobby"_

I believe this might be related to the merges from yesterday, as we did not have this issue before, but I'm not sure which change might have resulted in this. Maybe could be related to the [new feature of debug mode?](https://github.com/dhyegocalota/visa-appointment-tracker/commit/c56b499a9cd94d1bb9d9261ae215bb9ee5bb68b6) 

<img width="709" alt="image" src="https://user-images.githubusercontent.com/77297705/199220928-fbac820c-4f95-4841-b0ef-8da7c87d0693.png">

**Comment by dhyegocalota** [comment]
Thank you for the report. Seems like you tried to deploy using the Heroku button, right?

The issue seems like the `heroku/nodejs` buildpack has the `web` as the default dyno process but this app declares the a dyno called `cron` instead.

The buildpack's default dyno was using the `free` plan tier while the app was setting it to `hobby`. The rationale behind this app decision to use the `hobby` plan tier instead is because Heroku is going to [disable support](https://devcenter.heroku.com/articles/free-dyno-hours) for free tiers on November 28th.

We have a few of approaches to fix this error:

1. Set the app's dyno tier to `free` but it will work only until November 28th
2. Disable the buildpack's default dyno to avoid conflicts but requires a deeper exploration
3. Disable deployments using the Heroku button

Given the limited resources available, I implemented the first approach. It means that after November 28th, probably the Heroku deploy button will stop working anyways.
